{% set name = "openff-units" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-units/archive/{{ version }}.tar.gz
  sha256: 9a09704b73bfcb2651350bbdb28985130a8c521fe649a7a2cd7676d7c668c3a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - numpy
    - pint >=0.16.1
    - openff-utilities

test:
  requires:
    - setuptools
  imports:
    - openff.units
    - openff.units.simtk
    - openff.units.openmm
    - openff.units.elements

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  dev_url: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
