{% set org = "openforcefield" %}
{% set name = "openff-units" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<3.14.0a0
    - numpy
    - pint =0.24,<0.24.5  # only up to 0.24.4 has been tested, 0.24.5 or 0.25 not released
    - openff-utilities
  run_constrained:
    - openmm >7.6

test:
  requires:
    - python {{ python_min }}.*
    - setuptools
    - openmm
  imports:
    - openff.units
    - openff.units.openmm
    - openff.units.elements
  files:
    - test_units.py
  commands:
    - python test_units.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  dev_url: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
