{% set name = "openff-units" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-units/archive/{{ version }}.tar.gz
  sha256: b5bed06de07ed67b9659000946fcc3efda7fc92ade39f877f28e7ab46bd2d1a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.9,<3.13.0a0
    - numpy
    - pint >=0.21,<=0.23.0  # 0.21 or 0.22 or 0.23, but not 0.23.1 (unreleased as of 2024-03-25)
    - openff-utilities
  run_constrained:
    - openmm >7.6

test:
  requires:
    - setuptools
  imports:
    - openff.units
    - openff.units.openmm
    - openff.units.elements
  files:
    - test_units.py
  commands:
    - python test_units.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  dev_url: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
