{% set name = "openff-units" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-units/archive/{{ version }}.tar.gz
  sha256: 55296a1310d4a121fe204bad052ea4408f978a498256e98e73b247812329a2af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - numpy
    - pint >=0.16.1
    - openff-utilities

test:
  imports:
    - openff.units
    - openff.units.simtk
    - openff.units.openmm

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  dev_url: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
