{% set org = "openforcefield" %}
{% set name = "openff-units" %}
{% set version = "0.4.0beta1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f7c7d0e6d0934a8d344235979e8fc0b716bd905d0f31be7028ad1c45d5abda4d

build:
  noarch: python
  number: 0
  script:
    file: build_base.sh

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >={{ python_min }},<3.15.0a0
    - numpy
    - pint >=0.24.0,<0.26
    - openff-utilities
  run_constrained:
    - openmm >7.6
    - pydantic >=2.13  # 2.12 or older might also work

test:
  requires:
    - python {{ python_min }}.*
    - setuptools
    - openmm
  imports:
    - openff.units
    - openff.units.openmm
    - openff.units.elements
  files:
    - test_units.py
  commands:
    - python test_units.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  dev_url: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
